# Generated by Django 4.1.6 on 2023-03-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_recentlyposts_post_recentlyposts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.IntegerField(default=1),
        ),
    ]
