# Generated by Django 4.1.6 on 2023-03-25 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0012_alter_post_options_remove_post_body_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsforposts',
            options={'verbose_name': 'Связь новости и материала', 'verbose_name_plural': 'Связь новости и материала'},
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.CreateModel(
            name='ScriptsForPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('script', models.TextField()),
                ('operation', models.CharField(max_length=250)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
            options={
                'verbose_name': 'Скрипт и регистрация обращений',
                'verbose_name_plural': 'Скрипты и регистрации обращений',
            },
            managers=[
                ('scr_man', django.db.models.manager.Manager()),
            ],
        ),
    ]
