# Generated by Django 4.1.6 on 2023-03-25 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_scriptsforposts_type_alter_scriptsforposts_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsforposts',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
    ]
