# Generated by Django 4.1.6 on 2023-03-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_extendeduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='color_scheme',
            field=models.CharField(default='dark', max_length=100),
        ),
    ]
