# Generated by Django 4.2.1 on 2023-05-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_news_publish_alter_feedback_body'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='telegram_id',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
